// templates/pipelineTemplates.js — 12 pre-built pipeline templates
import { MarkerType } from 'reactflow';

const edge = (id, source, target, sourceHandle, targetHandle, label) => ({
    id,
    source,
    target,
    sourceHandle: sourceHandle ? `${source}-${sourceHandle}` : undefined,
    targetHandle: targetHandle ? `${target}-${targetHandle}` : undefined,
    type: 'smoothstep',
    animated: true,
    markerEnd: { type: MarkerType.ArrowClosed, height: 18, width: 18 },
    style: { strokeWidth: 2 },
    label,
    labelStyle: { fontSize: 10, fontWeight: 600 },
    labelBgStyle: { fill: '#f8fafc', fillOpacity: 0.85 },
});

export const PIPELINE_TEMPLATES = [
    // ─── AI ──────────────────────────────────────────────────────────────────
    {
        id: 'simple-qa',
        name: 'Simple Q&A',
        description: 'A basic question-answering pipeline: user input → text prompt → LLM → output.',
        category: 'AI',
        color: 'purple',
        emoji: '💬',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 160 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'user_question', inputType: 'Text' } },
            { id: 'text-1', type: 'text', position: { x: 340, y: 80 }, data: { id: 'text-1', nodeType: 'text', text: 'Answer the following question clearly:\n\n{{question}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 660, y: 140 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 960, y: 160 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'answer', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'text-1', 'value', 'question', 'question'),
            edge('e2', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e3', 'llm-1', 'customOutput-1', 'response', 'value', 'response'),
        ],
        nodeIDs: { customInput: 1, text: 1, llm: 1, customOutput: 1 },
    },
    {
        id: 'rag-pipeline',
        name: 'RAG Pipeline',
        description: 'Retrieval-Augmented Generation — combines a user query with retrieved context before calling the LLM.',
        category: 'AI',
        color: 'indigo',
        emoji: '🔍',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 50, y: 80 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'user_query', inputType: 'Text' } },
            { id: 'customInput-2', type: 'customInput', position: { x: 50, y: 280 }, data: { id: 'customInput-2', nodeType: 'customInput', inputName: 'context_docs', inputType: 'Text' } },
            { id: 'text-1', type: 'text', position: { x: 370, y: 160 }, data: { id: 'text-1', nodeType: 'text', text: 'Using the context below, answer the query.\n\nQuery: {{query}}\n\nContext:\n{{context}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 720, y: 160 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1020, y: 180 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'grounded_answer', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'text-1', 'value', 'query', 'query'),
            edge('e2', 'customInput-2', 'text-1', 'value', 'context', 'context'),
            edge('e3', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e4', 'llm-1', 'customOutput-1', 'response', 'value', 'response'),
        ],
        nodeIDs: { customInput: 2, text: 1, llm: 1, customOutput: 1 },
    },
    {
        id: 'multi-step-chain',
        name: 'Multi-Step LLM Chain',
        description: 'Chain two LLMs in sequence: first drafts a response, second refines and polishes the output.',
        category: 'AI',
        color: 'purple',
        emoji: '⛓️',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 200 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'topic', inputType: 'Text' } },
            { id: 'text-1', type: 'text', position: { x: 340, y: 120 }, data: { id: 'text-1', nodeType: 'text', text: 'Write a first draft about: {{topic}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 640, y: 140 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-3.5-turbo' } },
            { id: 'text-2', type: 'text', position: { x: 940, y: 120 }, data: { id: 'text-2', nodeType: 'text', text: 'Improve and polish this draft:\n\n{{draft}}' } },
            { id: 'llm-2', type: 'llm', position: { x: 1240, y: 140 }, data: { id: 'llm-2', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1540, y: 200 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'polished_output', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'text-1', 'value', 'topic', 'topic'),
            edge('e2', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e3', 'llm-1', 'text-2', 'response', 'draft', 'draft'),
            edge('e4', 'text-2', 'llm-2', 'output', 'prompt', 'refine'),
            edge('e5', 'llm-2', 'customOutput-1', 'response', 'value', 'final'),
        ],
        nodeIDs: { customInput: 1, text: 2, llm: 2, customOutput: 1 },
    },
    {
        id: 'customer-support-bot',
        name: 'Customer Support Bot',
        description: 'Routes a user message through a system-prompted LLM to generate a polite, on-brand support response.',
        category: 'AI',
        color: 'green',
        emoji: '🎧',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 100 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'customer_message', inputType: 'Text' } },
            { id: 'text-1', type: 'text', position: { x: 340, y: 60 }, data: { id: 'text-1', nodeType: 'text', text: 'You are a helpful customer support agent. Be concise, polite, and empathetic.' } },
            { id: 'text-2', type: 'text', position: { x: 340, y: 240 }, data: { id: 'text-2', nodeType: 'text', text: 'Customer says:\n{{message}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 680, y: 160 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'filter-1', type: 'filter', position: { x: 980, y: 180 }, data: { id: 'filter-1', nodeType: 'filter', condition: 'length > 10' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1260, y: 200 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'support_reply', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'text-1', 'llm-1', 'output', 'system', 'system'),
            edge('e2', 'customInput-1', 'text-2', 'value', 'message', 'message'),
            edge('e3', 'text-2', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e4', 'llm-1', 'filter-1', 'response', 'input', 'response'),
            edge('e5', 'filter-1', 'customOutput-1', 'output', 'value', 'reply'),
        ],
        nodeIDs: { customInput: 1, text: 2, llm: 1, filter: 1, customOutput: 1 },
    },
    {
        id: 'code-review',
        name: 'Code Review Assistant',
        description: 'Paste code and get an expert review with suggestions, bugs, and improvement recommendations.',
        category: 'AI',
        color: 'cyan',
        emoji: '🔬',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 80 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'code_snippet', inputType: 'Text' } },
            { id: 'customInput-2', type: 'customInput', position: { x: 60, y: 280 }, data: { id: 'customInput-2', nodeType: 'customInput', inputName: 'language', inputType: 'Text' } },
            { id: 'text-1', type: 'text', position: { x: 380, y: 160 }, data: { id: 'text-1', nodeType: 'text', text: 'Review the following {{lang}} code. Identify bugs, suggest improvements, and rate code quality:\n\n```\n{{code}}\n```' } },
            { id: 'llm-1', type: 'llm', position: { x: 720, y: 160 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'transform-1', type: 'transform', position: { x: 1020, y: 180 }, data: { id: 'transform-1', nodeType: 'transform', transformFn: 'Format as structured markdown with headers: Bugs, Improvements, Rating' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1320, y: 200 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'code_review', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'text-1', 'value', 'code', 'code'),
            edge('e2', 'customInput-2', 'text-1', 'value', 'lang', 'lang'),
            edge('e3', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e4', 'llm-1', 'transform-1', 'response', 'input', 'review'),
            edge('e5', 'transform-1', 'customOutput-1', 'output', 'value', 'formatted'),
        ],
        nodeIDs: { customInput: 2, text: 1, llm: 1, transform: 1, customOutput: 1 },
    },
    {
        id: 'translation',
        name: 'Language Translator',
        description: 'Translate text from any language to a target language, with style preservation.',
        category: 'AI',
        color: 'amber',
        emoji: '🌍',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 100 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'source_text', inputType: 'Text' } },
            { id: 'customInput-2', type: 'customInput', position: { x: 60, y: 280 }, data: { id: 'customInput-2', nodeType: 'customInput', inputName: 'target_language', inputType: 'Text' } },
            { id: 'text-1', type: 'text', position: { x: 360, y: 160 }, data: { id: 'text-1', nodeType: 'text', text: 'Translate the following text to {{lang}}. Preserve tone and style:\n\n{{text}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 700, y: 160 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1000, y: 180 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'translated_text', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'text-1', 'value', 'text', 'text'),
            edge('e2', 'customInput-2', 'text-1', 'value', 'lang', 'lang'),
            edge('e3', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e4', 'llm-1', 'customOutput-1', 'response', 'value', 'translated'),
        ],
        nodeIDs: { customInput: 2, text: 1, llm: 1, customOutput: 1 },
    },

    // ─── Data ─────────────────────────────────────────────────────────────────
    {
        id: 'data-transform',
        name: 'Data Transform & Filter',
        description: 'Clean, normalize, and filter raw input data before writing it to the output.',
        category: 'Data',
        color: 'amber',
        emoji: '🔧',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 160 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'raw_data', inputType: 'Text' } },
            { id: 'transform-1', type: 'transform', position: { x: 360, y: 100 }, data: { id: 'transform-1', nodeType: 'transform', transformFn: 'Normalize whitespace and strip HTML tags' } },
            { id: 'filter-1', type: 'filter', position: { x: 660, y: 160 }, data: { id: 'filter-1', nodeType: 'filter', condition: 'length > 0' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 960, y: 160 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'clean_data', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'transform-1', 'value', 'input', 'raw'),
            edge('e2', 'transform-1', 'filter-1', 'output', 'input', 'data'),
            edge('e3', 'filter-1', 'customOutput-1', 'output', 'value', 'filtered'),
        ],
        nodeIDs: { customInput: 1, transform: 1, filter: 1, customOutput: 1 },
    },
    {
        id: 'split-analyze-join',
        name: 'Split → Analyze → Join',
        description: 'Split a document into two parts, analyze each independently with an LLM, then merge the results.',
        category: 'Data',
        color: 'cyan',
        emoji: '✂️',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 220 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'document', inputType: 'Text' } },
            { id: 'split-1', type: 'split', position: { x: 360, y: 180 }, data: { id: 'split-1', nodeType: 'split', delimiter: '\\n\\n' } },
            { id: 'text-1', type: 'text', position: { x: 660, y: 80 }, data: { id: 'text-1', nodeType: 'text', text: 'Analyze part 1:\n\n{{part}}' } },
            { id: 'text-2', type: 'text', position: { x: 660, y: 320 }, data: { id: 'text-2', nodeType: 'text', text: 'Analyze part 2:\n\n{{part}}' } },
            { id: 'join-1', type: 'join', position: { x: 960, y: 200 }, data: { id: 'join-1', nodeType: 'join', separator: '\\n---\\n' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1260, y: 220 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'analysis', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'split-1', 'value', 'input', 'input'),
            edge('e2', 'split-1', 'text-1', 'output1', 'part', 'part 1'),
            edge('e3', 'split-1', 'text-2', 'output2', 'part', 'part 2'),
            edge('e4', 'text-1', 'join-1', 'output', 'input1', 'left'),
            edge('e5', 'text-2', 'join-1', 'output', 'input2', 'right'),
            edge('e6', 'join-1', 'customOutput-1', 'output', 'value', 'result'),
        ],
        nodeIDs: { customInput: 1, split: 1, text: 2, join: 1, customOutput: 1 },
    },
    {
        id: 'document-summarizer',
        name: 'Document Summarizer',
        description: 'Split a long document into chunks, summarize each with an LLM, then join into a final executive summary.',
        category: 'Data',
        color: 'indigo',
        emoji: '📄',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 220 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'long_document', inputType: 'Text' } },
            { id: 'split-1', type: 'split', position: { x: 360, y: 180 }, data: { id: 'split-1', nodeType: 'split', delimiter: '\\n\\n', maxSplits: 2 } },
            { id: 'text-1', type: 'text', position: { x: 660, y: 80 }, data: { id: 'text-1', nodeType: 'text', text: 'Summarize this section in 2–3 sentences:\n\n{{chunk}}' } },
            { id: 'text-2', type: 'text', position: { x: 660, y: 320 }, data: { id: 'text-2', nodeType: 'text', text: 'Summarize this section in 2–3 sentences:\n\n{{chunk}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 960, y: 80 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'llm-2', type: 'llm', position: { x: 960, y: 320 }, data: { id: 'llm-2', nodeType: 'llm', model: 'gpt-4o' } },
            { id: 'join-1', type: 'join', position: { x: 1260, y: 200 }, data: { id: 'join-1', nodeType: 'join', separator: '\\n\\n' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1560, y: 220 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'executive_summary', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'split-1', 'value', 'input', 'doc'),
            edge('e2', 'split-1', 'text-1', 'output1', 'chunk', 'chunk 1'),
            edge('e3', 'split-1', 'text-2', 'output2', 'chunk', 'chunk 2'),
            edge('e4', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e5', 'text-2', 'llm-2', 'output', 'prompt', 'prompt'),
            edge('e6', 'llm-1', 'join-1', 'response', 'input1', 'sum 1'),
            edge('e7', 'llm-2', 'join-1', 'response', 'input2', 'sum 2'),
            edge('e8', 'join-1', 'customOutput-1', 'output', 'value', 'summary'),
        ],
        nodeIDs: { customInput: 1, split: 1, text: 2, llm: 2, join: 1, customOutput: 1 },
    },

    // ─── Automation ───────────────────────────────────────────────────────────
    {
        id: 'api-and-summarize',
        name: 'API Fetch & Summarize',
        description: 'Fetch data from an external REST API, then summarize the response using an LLM.',
        category: 'Automation',
        color: 'rose',
        emoji: '🌐',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 160 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'endpoint', inputType: 'Text' } },
            { id: 'api-1', type: 'api', position: { x: 360, y: 120 }, data: { id: 'api-1', nodeType: 'api', method: 'GET', url: 'https://api.example.com/data' } },
            { id: 'text-1', type: 'text', position: { x: 660, y: 80 }, data: { id: 'text-1', nodeType: 'text', text: 'Summarize this API response in 3 bullet points:\n\n{{api_result}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 960, y: 140 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-3.5-turbo' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1260, y: 160 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'summary', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'api-1', 'value', 'request', 'endpoint'),
            edge('e2', 'api-1', 'text-1', 'response', 'api_result', 'result'),
            edge('e3', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e4', 'llm-1', 'customOutput-1', 'response', 'value', 'summary'),
        ],
        nodeIDs: { customInput: 1, api: 1, text: 1, llm: 1, customOutput: 1 },
    },
    {
        id: 'sentiment-pipeline',
        name: 'Sentiment Analysis',
        description: 'Ingest user reviews, clean the data, classify sentiment with an LLM, and filter only negative entries.',
        category: 'Automation',
        color: 'amber',
        emoji: '📊',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 180 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'review_text', inputType: 'Text' } },
            { id: 'transform-1', type: 'transform', position: { x: 360, y: 140 }, data: { id: 'transform-1', nodeType: 'transform', transformFn: 'Strip emojis and normalize punctuation' } },
            { id: 'text-1', type: 'text', position: { x: 660, y: 80 }, data: { id: 'text-1', nodeType: 'text', text: 'Classify the sentiment of the following review as POSITIVE, NEUTRAL, or NEGATIVE. Reply with only one word.\n\nReview: {{review}}' } },
            { id: 'llm-1', type: 'llm', position: { x: 980, y: 140 }, data: { id: 'llm-1', nodeType: 'llm', model: 'gpt-3.5-turbo' } },
            { id: 'filter-1', type: 'filter', position: { x: 1280, y: 180 }, data: { id: 'filter-1', nodeType: 'filter', condition: 'value == "NEGATIVE"' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1560, y: 200 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'sentiment_result', outputType: 'Text' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'transform-1', 'value', 'input', 'raw'),
            edge('e2', 'transform-1', 'text-1', 'output', 'review', 'clean'),
            edge('e3', 'text-1', 'llm-1', 'output', 'prompt', 'prompt'),
            edge('e4', 'llm-1', 'filter-1', 'response', 'input', 'label'),
            edge('e5', 'filter-1', 'customOutput-1', 'output', 'value', 'result'),
        ],
        nodeIDs: { customInput: 1, transform: 1, text: 1, llm: 1, filter: 1, customOutput: 1 },
    },
    {
        id: 'webhook-processor',
        name: 'Webhook Event Processor',
        description: 'Receive a webhook payload, validate it, transform the data, then POST it to another endpoint.',
        category: 'Automation',
        color: 'rose',
        emoji: '🔔',
        nodes: [
            { id: 'customInput-1', type: 'customInput', position: { x: 60, y: 180 }, data: { id: 'customInput-1', nodeType: 'customInput', inputName: 'webhook_payload', inputType: 'Text' } },
            { id: 'transform-1', type: 'transform', position: { x: 360, y: 140 }, data: { id: 'transform-1', nodeType: 'transform', transformFn: 'Parse JSON and extract relevant fields' } },
            { id: 'filter-1', type: 'filter', position: { x: 660, y: 160 }, data: { id: 'filter-1', nodeType: 'filter', condition: 'event_type == "order.completed"' } },
            { id: 'transform-2', type: 'transform', position: { x: 960, y: 140 }, data: { id: 'transform-2', nodeType: 'transform', transformFn: 'Map fields to the downstream API schema' } },
            { id: 'api-1', type: 'api', position: { x: 1260, y: 130 }, data: { id: 'api-1', nodeType: 'api', method: 'POST', url: 'https://internal.example.com/process' } },
            { id: 'customOutput-1', type: 'customOutput', position: { x: 1560, y: 180 }, data: { id: 'customOutput-1', nodeType: 'customOutput', outputName: 'api_response', outputType: 'JSON' } },
        ],
        edges: [
            edge('e1', 'customInput-1', 'transform-1', 'value', 'input', 'payload'),
            edge('e2', 'transform-1', 'filter-1', 'output', 'input', 'parsed'),
            edge('e3', 'filter-1', 'transform-2', 'output', 'input', 'event'),
            edge('e4', 'transform-2', 'api-1', 'output', 'request', 'body'),
            edge('e5', 'api-1', 'customOutput-1', 'response', 'value', 'result'),
        ],
        nodeIDs: { customInput: 1, transform: 2, filter: 1, api: 1, customOutput: 1 },
    },
];
